/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca__1360_liborbit_util_jni_OrbitInputEventsReader */

#ifndef _Included_ca__1360_liborbit_util_jni_OrbitInputEventsReader
#define _Included_ca__1360_liborbit_util_jni_OrbitInputEventsReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca__1360_liborbit_util_jni_OrbitInputEventsReader
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca__11360_liborbit_util_jni_OrbitInputEventsReader_run
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
