/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca__1360_liborbit_io_OrbitLocalJoystickProvider */

#ifndef _Included_ca__1360_liborbit_io_OrbitLocalJoystickProvider
#define _Included_ca__1360_liborbit_io_OrbitLocalJoystickProvider
#ifdef __cplusplus
extern "C" {
#endif
  /*
  * Class:     ca__1360_liborbit_io_OrbitLocalJoystickProvider
  * Method:    getName
  * Signature: ()Ljava/lang/String;
  */
  JNIEXPORT jstring JNICALL Java_ca__11360_liborbit_io_OrbitLocalJoystickProvider_getName
  (JNIEnv *, jobject);

  /*
  * Class:     ca__1360_liborbit_io_OrbitLocalJoystickProvider
  * Method:    getAxis
  * Signature: (I)D
  */
  JNIEXPORT jdouble JNICALL Java_ca__11360_liborbit_io_OrbitLocalJoystickProvider_getAxis
  (JNIEnv *, jobject, jint);

  /*
  * Class:     ca__1360_liborbit_io_OrbitLocalJoystickProvider
  * Method:    getButton
  * Signature: (I)Z
  */
  JNIEXPORT jboolean JNICALL Java_ca__11360_liborbit_io_OrbitLocalJoystickProvider_getButton
  (JNIEnv *, jobject, jint);

  /*
  * Class:     ca__1360_liborbit_io_OrbitLocalJoystickProvider
  * Method:    getPov
  * Signature: (I)I
  */
  JNIEXPORT jint JNICALL Java_ca__11360_liborbit_io_OrbitLocalJoystickProvider_getPov
  (JNIEnv *, jobject, jint);

  /*
  * Class:     ca__1360_liborbit_io_OrbitLocalJoystickProvider
  * Method:    setOutput
  * Signature: (IZ)V
  */
  JNIEXPORT void JNICALL Java_ca__11360_liborbit_io_OrbitLocalJoystickProvider_setOutput
  (JNIEnv *, jobject, jint, jboolean);

  /*
  * Class:     ca__1360_liborbit_io_OrbitLocalJoystickProvider
  * Method:    refresh
  * Signature: ()[Z
  */
  JNIEXPORT jbooleanArray JNICALL Java_ca__11360_liborbit_io_OrbitLocalJoystickProvider_refresh
  (JNIEnv *, jclass);

  /*
  * Class:     ca__1360_liborbit_io_OrbitLocalJoystickProvider
  * Method:    reorder
  * Signature: (II)V
  */
  JNIEXPORT void JNICALL Java_ca__11360_liborbit_io_OrbitLocalJoystickProvider_reorder
  (JNIEnv *, jclass, jint, jint);

  /*
  * Class:     ca__1360_liborbit_io_OrbitLocalJoystickProvider
  * Method:    setup
  * Signature: ()V
  */
  JNIEXPORT void JNICALL Java_ca__11360_liborbit_io_OrbitLocalJoystickProvider_setup
  (JNIEnv *, jobject);

  /*
  * Class:     ca__1360_liborbit_io_OrbitLocalJoystickProvider
  * Method:    initialize
  * Signature: ()V
  */
  JNIEXPORT void JNICALL Java_ca__11360_liborbit_io_OrbitLocalJoystickProvider_initialize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
